/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lostsidedead_acidcam_AcidCam_Filter */

#ifndef _Included_com_lostsidedead_acidcam_AcidCam_Filter
#define _Included_com_lostsidedead_acidcam_AcidCam_Filter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lostsidedead_acidcam_AcidCam_Filter
 * Method:    Filter
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_lostsidedead_acidcam_AcidCam_1Filter_Filter
  (JNIEnv *, jobject, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
